"""create table badges

Revision ID: 5f57115e6a02
Revises: fe793b18398c
Create Date: 2026-05-23 02:41:59.665474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f57115e6a02'
down_revision: Union[str, Sequence[str], None] = 'fe793b18398c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Badges',
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, erver_default=sa.text('CURRENT_TIMESTAMP')),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('User_Badge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['Badges.badge_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_Badge')
    op.drop_table('Badges')
    # ### end Alembic commands ###
